version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./.local-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
